language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
      dist: xenial
      sudo: true
install:
- pip install coverage
- pip install coveralls
script:
 - cd test
 - env PYTHONPATH=.. python -m unittest --verbose all
 - cd ..
 - env PYTHONPATH=. coverage run test/all.py
after_success:
 - coveralls
